### ISSUE TITLE
[FEAT] - Display files directly in 'Manuel Qualité'

### ISSUE THREAD

**Issue by raphpay** [raphpay/GladIs-Client-App#139]
### Summary

The page 'Manuel Qualité' should directly display documents instead of categories. 

## TODOs
- [x] Verify the existing files
- [x] Move files that are placed inside ManuelQualité/ProcessusX/ into ManuelQualité/

**Comment by raphpay** [comment]
- [ ] Add a parameter to folders to display files correctly ( [API Issue 80](https://github.com/raphpay/GladIs-API/issues/80) )
- [ ] Adapt the client for the new navigation
